# Generated by Django 2.2 on 2021-12-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IDC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='机房名称')),
                ('address', models.CharField(max_length=256, verbose_name='机房地址')),
                ('phone', models.CharField(max_length=15, verbose_name='机房联系电话')),
                ('email', models.EmailField(default='null', max_length=254, verbose_name='机房email')),
                ('letter', models.CharField(max_length=5, verbose_name='IDC机房简称')),
            ],
            options={
                'db_table': 'resources_idc',
            },
        ),
    ]
