# Generated by Django 2.2 on 2021-09-25 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idcs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idc',
            name='email',
            field=models.EmailField(default='null', max_length=254, verbose_name='机房email'),
        ),
    ]
