# Generated by Django 2.2 on 2021-10-05 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0003_auto_20211005_1401'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='rmt_card_ip',
            field=models.CharField(db_index=True, help_text='远程管理IP', max_length=15, null=True, unique=True, verbose_name='远程管理卡IP'),
        ),
    ]
