# Generated by Django 2.2 on 2021-12-11 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servers', '0004_auto_20211005_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='uuid',
            field=models.CharField(db_index=True, help_text='UUID', max_length=80, unique=True, verbose_name='UUID'),
        ),
    ]
