# Generated by Django 2.2 on 2021-10-05 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manufacturer', '0002_auto_20211005_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='model_name',
            field=models.CharField(help_text='型号名称', max_length=40, verbose_name='型号名称'),
        ),
    ]
